### ISSUE TITLE
Adaptor throws an error on Windows fleet instance

### ISSUE THREAD

**Issue by andymanaws** [aws-deadline/deadline-cloud-for-maya#159]
### Expected Behaviour

This appears to be a significant error stopping the execution of a job

### Current Behaviour

During the processing of a job running on Windows I get the following error:

```
2024/06/13 11:40:29+00:00 openjd_fail: Error encountered while starting adaptor: Objects of type 'WindowsPath' can not be converted to Unicode.
2024/06/13 11:40:29+00:00 ERROR: Entrypoint failed: openjd_fail: Error encountered while starting adaptor: Objects of type 'WindowsPath' can not be converted to Unicode.
```

### Reproduction Steps

I believe you just need to run the adaptor on a Windows machine.

Full error log attached:
[maya_cmf.txt](https://github.com/user-attachments/files/15820707/maya_cmf.txt)

### Code Snippet

NA

**Comment by jblagden** [comment]
Chiming in, I've also encountered this issue on a completely new machine so at the very least we know it's not an issue with the machine.

**Comment by jusiskin** [comment]
Thank you, @andymanaws for bringing this issue to our attention.

To help us diagnose this problem further, could you please provide some additional information about your setup? It would help to know a few of the versions of software being used on your Windows CMF workers:

*   Maya version
*   `deadline-cloud-for-maya` version
*   `openjd-adaptor-runtime` version

Thanks!

**Comment by jericht** [comment]
Thanks for reporting the issue! This issue was most likely due to a bug in the [`openjd-adaptor-runtime` package](https://github.com/OpenJobDescription/openjd-adaptor-runtime-for-python) and has been fixed as of testing for the latest release.
