### ISSUE TITLE
Bug: Maya / Deadline gui resubmit resolution bug

### ISSUE THREAD

**Issue by aws-cris** [aws-deadline/deadline-cloud-for-maya#178]
### Describe the bug

The Deadline Cloud gui resubmit feature has fields for changing the resolution (width and height values) of the rendered output upon re-submission of a job bundle, however, the job still render the output at the original submission resolution values. 

### Expected Behaviour

I would expect that if the user uses the gui submitter to submit a previous job bundle, and then updates the resolution fields that the render output resolutions reflect that update. 

### Current Behaviour

The user can change the values of resolution in the gui submitter, the values show up in the job monitor when viewing the job properties, but the resolution of the output remains the same as the values in the job bundle. 

### Reproduction Steps

1. Create a job bundle submission from Maya 2024 that has a render output resolution of 5760 x 3240. 
2. Use the deadline gui submitter to submit the job. In the gui submitter, change the resolution to 2880x1620. 
3. See that the output resolution is still 5760x3240. 

### Environment

At minimum:
1. Operating system:Windows Server 2022 as the submission OS; Amazon Linux 2023 as the rendering OS in Deadline Cloud
2. Version of Maya: 2024
3: Version of this package: the gui submitter comes from the CLI which is version 0.48.4
4. If this is from a version installed by the Deadline Cloud Submitter installer, then what version of the submitter installer?

Please share other details about your environment that you think might be relevant to reproducing the bug.

**Comment by crowecawcaw** [comment]
After poking around, this should be fixed by: https://github.com/aws-deadline/deadline-cloud-for-maya/pull/176

The fix should go out with the next release.
