### ISSUE TITLE
Docs: Submitter installation directions are incomplete

### ISSUE THREAD

**Issue by yuanmich2** [aws-deadline/deadline-cloud-for-maya#182]
### Documentation Issue

The [submitter installation directions](https://github.com/aws-deadline/deadline-cloud-for-maya/blob/419a06b73b1b4914561e36e97c95a5e325c61762/README.md?plain=1#L57-L73) are incomplete.

The first two steps have external links that lead to 404s. They should probably point to these urls instead:
https://help.autodesk.com/view/MAYAUL/2025/ENU/?guid=GUID-72A245EC-CDB4-46AB-BEE0-4BBBF9791627
https://help.autodesk.com/view/MAYAUL/2025/ENU/?guid=GUID-228CCA33-4AFE-4380-8C3D-18D23F7EAC72

When I followed steps 1 and 2 on a Mac with Maya 2024, I ended up not being able to find the deadline cloud plugin in step 3. This is probably because the instructions omit setting up the plugin (different from module). To do that you need to set the following environment variables:
```
MAYA_PLUG_IN_PATH = /<full path to directory_name>/deadline/maya_submitter/maya_submitter_plugin/plug-ins
MAYA_SCRIPT_PATH = /<full path to directory_name>/
PYTHONPATH = /<full path to directory_name>/
XBMLANGPATH = /<full path to directory_name>/deadline/maya_submitter/maya_submitter_plugin/icons
```
<full path to directory_name> should be wherever the python packages were installed. You can find the location of your packages with `mayapy -m pip show deadline-cloud-for-maya`

There may be other changes needed

**Comment by dzavada** [comment]
Set up a variable to specify the location where the plug-in is installed.
set your MAYA_MODULE_PATH= /<full path to directory_name>/deadline/maya_submitter/maya_submitter_plugin/plug-ins

**Comment by yuanmich2** [comment]
We need to set MAYA_PLUG_IN_PATH and MAYA_MODULE_PATH to the same directory?

**Comment by sakshie95** [comment]
Thanks @yuanmich2 @dzavada for creating this issue. We appreciate the time take by the community supporting the product.

We'll be taking a look at this on our end.

**Comment by benl-2023** [comment]
I've created a PR that will fix the broken documentation links in the README.
